service: handswers-backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true

custom:
  dotenv:
    path: .env.${opt:stage, 'dev'}
  esbuild:
    bundle: true
    minify: false #Set to true in production
    sourcemap: true #Set to false in production
    target: node18
    platform: node
    concurrency: 10

functions:
  api:
    handler: src/handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any
